/**
 * Content Script — Lockstep Sync (FR-3)
 * Keeps DOM-based and screenshot-based redaction in sync.
 *
 * Core operation: for every DOM node flagged sensitive by the DMPR engine,
 * look up its CURRENT bounding box (getBoundingClientRect) and return a
 * { nodeId, bbox, sensitivityLabel } mapping that the background worker uses
 * to paint placeholder boxes onto the screenshot before sending it out.
 *
 * Stage 0: structure and message handler in place; bbox resolution works.
 * Stage 3: called by the background worker after detections are available;
 *           background worker paints the boxes onto the screenshot bitmap.
 */

'use strict';

/**
 * Given a list of nodeIds (from DMPR detections), resolve each to its
 * current live bounding box.
 *
 * The background worker sends this request AFTER running detectSensitiveData
 * so that bboxes are always fresh (the page may have scrolled/reflowed since
 * the snapshot was taken).
 *
 * @param {string[]} nodeIds
 * @returns {Array<{ nodeId: string, bbox: { x, y, width, height }|null }>}
 */
function resolveBoxes(nodeIds) {
  return nodeIds.map(nid => {
    const el = findElementByNodeId(nid);
    if (!el) return { nodeId: nid, bbox: null };
    const r = el.getBoundingClientRect();
    return {
      nodeId: nid,
      bbox: { x: r.x, y: r.y, width: r.width, height: r.height }
    };
  });
}

/**
 * Find a DOM element by its nodeId string (as generated by capture.js).
 * Handles two formats:
 *   "#my-id"  → document.getElementById("my-id")
 *   "tag[n]/tag[n]/..."  → walk parent/children counts
 *
 * @param {string} nid
 * @returns {Element|null}
 */
function findElementByNodeId(nid) {
  if (nid.startsWith('#')) {
    return document.getElementById(nid.slice(1));
  }

  // XPath-style path: "input[2]/div[3]" etc.
  const parts = nid.split('/');
  let current = document.body;
  for (const part of parts) {
    const match = part.match(/^(\w+)\[(\d+)\]$/);
    if (!match) return null;
    const [, tag, idxStr] = match;
    const idx = parseInt(idxStr, 10) - 1; // convert to 0-based
    const children = Array.from(current.children).filter(
      c => c.tagName.toLowerCase() === tag
    );
    if (!children[idx]) return null;
    current = children[idx];
  }
  return current instanceof Element ? current : null;
}

/**
 * Build the full lockstep sync map for a given list of detections.
 * Returns enriched detections with bbox filled in.
 *
 * @param {Array<{ nodeId: string, label: string, risk: string }>} detections
 * @returns {Array<{ nodeId, label, risk, bbox }>}
 */
function buildLockstepMap(detections) {
  const nodeIds = [...new Set(detections.map(d => d.nodeId))];
  const bboxMap = Object.fromEntries(
    resolveBoxes(nodeIds).map(r => [r.nodeId, r.bbox])
  );

  return detections.map(det => ({
    ...det,
    bbox: bboxMap[det.nodeId] ?? null
  }));
}

// ─── Message listener ─────────────────────────────────────────────────────────

chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
  if (message.type === 'BUILD_LOCKSTEP_MAP') {
    try {
      const enriched = buildLockstepMap(message.detections ?? []);
      sendResponse({ ok: true, detections: enriched });
    } catch (err) {
      sendResponse({ ok: false, error: err.message });
    }
    return true;
  }

  if (message.type === 'RESOLVE_BBOX') {
    // Convenience: resolve a single nodeId to its current bbox.
    try {
      const el = findElementByNodeId(message.nodeId);
      if (!el) {
        sendResponse({ ok: false, bbox: null, error: 'Element not found' });
      } else {
        const r = el.getBoundingClientRect();
        sendResponse({ ok: true, bbox: { x: r.x, y: r.y, width: r.width, height: r.height } });
      }
    } catch (err) {
      sendResponse({ ok: false, bbox: null, error: err.message });
    }
    return true;
  }
});
